### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by nvilcins** [AbsoDev/FileEncryptor#15]
```
Line 18, 19: potential memory leak, same with 36, 37: 
new CryptoPP::StreamTransformationFilter(cbcDecryption,
    new CryptoPP::FileSink(out_file)
)
```

**Comment by vladimirslav** [comment]
Nevermind, this is not an issue.

From cryptopp documentation:
1. If a constructor for A takes a pointer to an object B (except primitive
   types such as int and char), then A owns B and will delete B at A's
   destruction.  If a constructor for A takes a reference to an object B,
   then the caller retains ownership of B and should not destroy it until
   A no longer needs it.
