### ISSUE TITLE
Backend - Random IV

### ISSUE THREAD

**Issue by nvilcins** [AbsoDev/FileEncryptor#3]
Currently we have hard-coded zero IV. Should be random and passed together with output.

**Comment by vladimirslav** [comment]
put it at the start of the encrypted file. Not the most secure option, but at least if someone encrypts the same file twice, he is going to get different results (which are still decrypted into one and the same file).

**Comment by nvilcins** [comment]
actually this is perfectly safe. iv is public data, it just should never repeat among multiple sessions.
added to the start of the file.
